### ISSUE TITLE
Incorrect definition of `primes`

### ISSUE THREAD

**Issue by Jubobs** [opqdonut/haskell-exercises#15]
# Problem
[The definition of `primes` in file `W1Test.hs`](https://github.com/opqdonut/haskell-exercises/blob/master/W1Test.hs#L173), i.e.

```haskell
primes = nubBy (\x y -> mod x y == 0) [2..]
```

is incorrect; for instance, if you load `W1Test.hs` in GHCi and evaluate

```haskell
take 5 primes
```
you get `[2,3,4,5,6]`. Because of this incorrect definition, tests for problems 17-19 fail, even on correct solutions.

# Solution

Replacing the incorrect definition by a correct one, e.g.

```haskell
primes = 2 : filter isPrime' [3, 5 ..]
  where
    isPrime' n
        | n < 2     = False
        | otherwise = all (\p -> n `mod` p /= 0) $
                          takeWhile (\p -> p ^ 2 <= n) primes
```

solves the problem.

**Comment by opqdonut** [comment]
Interesting, it works for me:

    Prelude Data.List> let primes = nubBy (\x y -> mod x y == 0) [2..]
    Prelude Data.List> take 5 primes
    [2,3,5,7,11]

**Comment by Jubobs** [comment]
That's very weird... This is what I get in GHCi 7.10.1:

```haskell
λ> :m + Data.List
λ> let primes = nubBy (\x y -> mod x y == 0) [2..]
λ> take 5 primes
[2,3,4,5,6]
```

**Comment by opqdonut** [comment]
I tried this in 7.6. Perhaps the order of arguments has been changed again in nubBy. I get `[2,3,4,5,6]` if I use `(\x y -> mod x y == 0)`.

I'll switch to a more robust definition of `primes` later today.

**Comment by Jubobs** [comment]
I'll check whether the definition of `nubBy` changed between 7.6 and 7.10.1, and I'll report here if I find anything.

**Comment by Jubobs** [comment]
After inspection of the [GHC repo](https://github.com/ghc/ghc), I found that the order of the arguments of `nubBy`'s first argument (a binary function) was reversed a first time in 2008 (see [0ad9def53842e86fb292eccb810190711c42d7c5](https://github.com/ghc/ghc/commit/0ad9def53842e86fb292eccb810190711c42d7c5)), but was subsequently reversed a second time in 2014 (see [a2e7bbfe7656cf7dbf1af4da5c077ac0b5d41127](https://github.com/ghc/ghc/commit/a2e7bbfe7656cf7dbf1af4da5c077ac0b5d41127)), after the release of GHC 7.6.
