### ISSUE TITLE
LICENSE for this repository

### ISSUE THREAD

**Issue by tqa236** [opqdonut/haskell-exercises#23]
Hello,

Thank you very much for your exercises. I would like to solve them and push to my repository for practising and employment purpose in the future. Can you specify a license for this project so that I will know if I have a right to do that or not? 

Best regards,
TRINH Quoc Anh

**Comment by opqdonut** [comment]
Thanks for pointing that out. I've added a CC-BY 4.0 license in 25a73a0.
