### ISSUE TITLE
Ambigious reference running W0test.hs

### ISSUE THREAD

**Issue by NaevaTheCat** [opqdonut/haskell-exercises#6]
After installing QuickCheck calling runhaskell W0test.hs returns

mpl/Test.hs:34:10:
    Ambiguous occurrence `==='
    It could refer to either `Impl.Test.===',
                             defined at Impl/Test.hs:35:8
                          or `Test.QuickCheck.===',
                             imported from `Test.QuickCheck' at Impl/Test.hs:4:1-45
                             (and originally defined in `Test.QuickCheck.Property')

Off a fresh install of haskell-platform.

**Comment by opqdonut** [comment]
I pushed a fix, try now.

**Comment by NaevaTheCat** [comment]
Solved tyvm.
